version: '3'
services:
  # mongoDB instance
  mongodb:
    image: mongo
    restart: always
    container_name: ${DB_NAME}
    ports:
      - "27017:27017"
    volumes:
      - /data/mongodb/data/db:/data/db
    networks:
      aesir_internal_docker_network:
        ipv4_address: 192.168.1.77

  # golang backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aesir_backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      DB_URL: ${DB_URL}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_ACCESS_FULL_URL: ${DB_ACCESS_FULL_URL}
    networks:
      aesir_internal_docker_network:
        ipv4_address: 192.168.1.100

networks:
  aesir_internal_docker_network:
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1
